anim-com
========

== Translations

The translation of our platform is managed on https://crwd.in/exodus-privacy[Crowdin]

== Videos

[horizontal]
[#video-en]*[en]* English::
This repository is used for the external communication from Exodus Privacy.
You will find the videos and more important, the subtitle files (in the folders `vidéos/xxx`).
If you want to help us to improve our subtitles or add your native language, do not hesitate, your contributions are welcome.
If you have a nice voice and are ready to dub those videos, once again, you’re welcome.
Fork this repo and ‘just do it’.

[#video-fr]*[fr]* Français::
Ce dépôt sert à la communication externe d'Exodus Privacy.
Vous y trouverez les vidéos et, plus important, les fichiers de sous-titres (dans les dossiers `vidéos/xxxx`).
Si vous avez une belle voix et l'envie de doubler les vidéos, votre aide est la bienvenue.
« Forkez » le dépôt et amusez-vous bien.

[#video-de]*[de]* Deutsch::
Dieses Repository wird für die externe Kommunikation von Exodus Privacy benutzt.
Die Videos und viel wichtiger die Untertitel Dateien findest du in (`vidéos/xxx` Verzeichnis).
Wenn du uns helfen möchtest, unsere Untertitel zu verbessen oder deine Muttersprache hinzuzufügen, zögere nicht, dein Beitrag ist stets willkommen.
Wenn du eine nette Stimme hast und bereit bist diese Videos zu synchronisieren, nur zu.
Fork dir dieses Repo und „just do it“.
